# Generated by Django 3.1.7 on 2021-06-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lastname',
            field=models.CharField(default='kapoor', max_length=200),
            preserve_default=False,
        ),
    ]
