# Generated by Django 3.1.7 on 2021-06-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
